version: "3.9"

services:
  web:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "6006:6006"
    volumes:
      - ./src:/app/src
    # networks:
    #   - home-networks
    environment:
      - WATCHPACK_POLLING=true
      # - CHOKIDAR_USEPOLLING=true

# networks:
#   home-networks:
#     name: home-network
#     external: false